name: Nx check changes
description: GitHub Action that checks if a code change affects any app or lib in a Nx workspace.
branding:
  icon: folder
  color: blue
runs:
  using: 'node16'
  main:  'dist/index.js'
inputs:
  baseRef:
    description: Ref to the base.
  headRef:
    description: Ref to the head.
outputs:
  changed-apps:
    description: Space-delimited string of changed apps
  changed-libs:
    description: Space-delimited string of changed libs
  changed-dirs:
    description: Space-delimited string of changed apps and libs
  not-affected:
    description: Whether or not code changes affect the apps or libs
